const GroupSubstitutionEncodeTable: [string, string][] = [
    ['A', 'AAA'],
    ['B', 'AAC'],
    ['C', 'ABB'],
    ['D', 'ACA'],
    ['E', 'ACC'],
    ['F', 'BAB'],
    ['G', 'BBA'],
    ['H', 'BBC'],
    ['I', 'BCB'],
    ['J', 'CAA'],
    ['K', 'CAC'],
    ['L', 'CBB'],
    ['M', 'CCA'],
    ['N', 'CCC'],
    ['O', 'CBC'],
    ['P', 'CBA'],
    ['Q', 'CAB'],
    ['R', 'BCC'],
    ['S', 'BCA'],
    ['T', 'BBB'],
    ['U', 'BAC'],
    ['V', 'BAA'],
    ['W', 'ACB'],
    ['X', 'ABC'],
    ['Y', 'ABA'],
    ['Z', 'AAB'],
    [' ', 'CCB'],
];
const GroupSubstitutionDecodeTable: [string, string][] = [
    ['AAA', 'A'],
    ['AAC', 'B'],
    ['ABB', 'C'],
    ['ACA', 'D'],
    ['ACC', 'E'],
    ['BAB', 'F'],
    ['BBA', 'G'],
    ['BBC', 'H'],
    ['BCB', 'I'],
    ['CAA', 'J'],
    ['CAC', 'K'],
    ['CBB', 'L'],
    ['CCA', 'M'],
    ['CCC', 'N'],
    ['CBC', 'O'],
    ['CBA', 'P'],
    ['CAB', 'Q'],
    ['BCC', 'R'],
    ['BCA', 'S'],
    ['BBB', 'T'],
    ['BAC', 'U'],
    ['BAA', 'V'],
    ['ACB', 'W'],
    ['ABC', 'X'],
    ['ABA', 'Y'],
    ['AAB', 'Z'],
    ['CCB', ' '],
];

export const GroupSubstitutionEncodeMap: Map<string, string> = new Map<string, string>(GroupSubstitutionEncodeTable);
export const GroupSubstitutionDecodeMap: Map<string, string> = new Map<string, string>(GroupSubstitutionDecodeTable);

export const playfairMatrix: string[][] = [
    ['P', 'L', 'A', 'Y', 'F'],
    ['I', 'R', 'E', 'X', 'M'],
    ['B', 'C', 'D', 'G', 'H'],
    ['K', 'N', 'O', 'Q', 'S'],
    ['T', 'U', 'V', 'W', 'Z'],
  ];
